disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- todo
- identifier_name
- shorthand_operator
- control_statement
- syntactic_sugar
- line_length
- unused_closure_parameter
- implicit_getter
- redundant_optional_initialization
- cyclomatic_complexity
- multiple_closures_with_trailing_closure
# implicitly
line_length: 200
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

