name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: testing ... iPhone 12
      run: xcodebuild clean test -project TheGamesApps.xcodeproj -scheme TheGamesApps -destination "platform=iOS Simulator,name=iPhone 12 Pro Max"
