name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
           xcodebuild clean build -project "TheGamesApps.xcodeproj" -scheme "TheGamesApps" -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
     
